INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');

INSERT INTO room_status(name) VALUES('ROOM_STATUS_VACANT');
INSERT INTO room_status(name) VALUES('ROOM_STATUS_BOOKED');
INSERT INTO room_status(name) VALUES('ROOM_STATUS_OCCUPIED');
INSERT INTO room_status(name) VALUES('ROOM_STATUS_OUTOFSERVICE');

INSERT INTO amenity_status(name) VALUES('AMENITY_STATUS_FOOD');
INSERT INTO amenity_status(name) VALUES('AMENITY_STATUS_FUN');
INSERT INTO amenity_status(name) VALUES('AMENITY_STATUS_LIFESTYLE');
INSERT INTO amenity_status(name) VALUES('AMENITY_STATUS_BAR');