@startuml
participant Actor
Actor -> ReservationController : getAll
activate ReservationController

ReservationController -> ReservationService: getAll
activate ReservationService

ReservationService -> ReservationDAO: getAll
activate ReservationDAO

ReservationDAO -> ReservationRepository
activate ReservationRepository

ReservationRepository --> ReservationDAO
deactivate ReservationRepository

ReservationDAO --> ReservationService
deactivate ReservationDAO

ReservationService --> ReservationController
deactivate ReservationService

return
@enduml