@startuml
participant Actor
Actor -> ReservationController : getById
activate ReservationController

ReservationController -> ReservationService: getById
activate ReservationService

ReservationService -> ReservationDAO: getById
activate ReservationDAO

ReservationDAO -> ReservationRepository: getById
activate ReservationRepository

ReservationRepository --> ReservationDAO
deactivate ReservationRepository

ReservationDAO --> ReservationService
deactivate ReservationDAO

ReservationService --> ReservationController
deactivate ReservationService

return
@enduml